/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ChoiceService } from "../choice.service";
import { ChoiceCreateInput } from "./ChoiceCreateInput";
import { Choice } from "./Choice";
import { ChoiceFindManyArgs } from "./ChoiceFindManyArgs";
import { ChoiceWhereUniqueInput } from "./ChoiceWhereUniqueInput";
import { ChoiceUpdateInput } from "./ChoiceUpdateInput";

export class ChoiceControllerBase {
  constructor(protected readonly service: ChoiceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Choice })
  async createChoice(@common.Body() data: ChoiceCreateInput): Promise<Choice> {
    return await this.service.createChoice({
      data: {
        ...data,

        scene: data.scene
          ? {
              connect: data.scene,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        nextScene: true,

        scene: {
          select: {
            id: true,
          },
        },

        text: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Choice] })
  @ApiNestedQuery(ChoiceFindManyArgs)
  async choices(@common.Req() request: Request): Promise<Choice[]> {
    const args = plainToClass(ChoiceFindManyArgs, request.query);
    return this.service.choices({
      ...args,
      select: {
        createdAt: true,
        id: true,
        nextScene: true,

        scene: {
          select: {
            id: true,
          },
        },

        text: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Choice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async choice(
    @common.Param() params: ChoiceWhereUniqueInput
  ): Promise<Choice | null> {
    const result = await this.service.choice({
      where: params,
      select: {
        createdAt: true,
        id: true,
        nextScene: true,

        scene: {
          select: {
            id: true,
          },
        },

        text: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Choice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateChoice(
    @common.Param() params: ChoiceWhereUniqueInput,
    @common.Body() data: ChoiceUpdateInput
  ): Promise<Choice | null> {
    try {
      return await this.service.updateChoice({
        where: params,
        data: {
          ...data,

          scene: data.scene
            ? {
                connect: data.scene,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          nextScene: true,

          scene: {
            select: {
              id: true,
            },
          },

          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Choice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteChoice(
    @common.Param() params: ChoiceWhereUniqueInput
  ): Promise<Choice | null> {
    try {
      return await this.service.deleteChoice({
        where: params,
        select: {
          createdAt: true,
          id: true,
          nextScene: true,

          scene: {
            select: {
              id: true,
            },
          },

          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
