/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ChoiceListRelationFilter } from "../../choice/base/ChoiceListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { ProgressListRelationFilter } from "../../progress/base/ProgressListRelationFilter";
import { TimerListRelationFilter } from "../../timer/base/TimerListRelationFilter";

@InputType()
class SceneWhereInput {
  @ApiProperty({
    required: false,
    type: () => ChoiceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ChoiceListRelationFilter)
  @IsOptional()
  @Field(() => ChoiceListRelationFilter, {
    nullable: true,
  })
  choices?: ChoiceListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  content?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isCheckpoint?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ProgressListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProgressListRelationFilter)
  @IsOptional()
  @Field(() => ProgressListRelationFilter, {
    nullable: true,
  })
  progresses?: ProgressListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TimerListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TimerListRelationFilter)
  @IsOptional()
  @Field(() => TimerListRelationFilter, {
    nullable: true,
  })
  timers?: TimerListRelationFilter;
}

export { SceneWhereInput as SceneWhereInput };
